serial:
  port: COM20
  baud_rate: 9600
  parity: N
  data_bits: '8'
  stop_bits: '1'
buttons:
- id: test-btn
  label: TEST
  message: "TEST\r\n"
  format: ascii
  tooltip: Test button
  repeat: 2000
- id: PING
  label: PING
  message: ":CR001PING\r\n"
  format: ascii
sequences:
- name: ACK Response
  active: true
  delay: 0
  receive:
    data: '06'
    format: hex
  send:
    data: '06'
    format: hex
  comment: ACK Received
ui:
  theme: gruvbox
